name: TestLab Predict
description: Predict CI results

inputs:
  predicted-file:
    description: Path to the predicted tests file.
    default: /tmp/testlab-predicted.txt
    required: false
  runner:
    description: Name of the test runner format.
    required: true
  list-command:
    description: Command to list test names used as input for prediction.
    required: true
  repo-root:
    description: Root directory of the repository.
    required: false
  continue-on-error:
    description: Continue with CI workflow on error.
    type: boolean
    required: false
    default: true

runs:
  using: composite
  steps:
    - name: Predict CI results
      run: ${GITHUB_ACTION_PATH}/script.sh
      shell: bash
      continue-on-error: ${{ fromJSON(inputs.continue-on-error) }}
      env:
        PREDICTED_FILE: ${{ inputs.predicted-file }}
        LIST_COMMAND: ${{ inputs.list-command }}
        RUNNER: ${{ inputs.runner }}
        REPO_ROOT: ${{ inputs.repo-root || github.workspace }}
