name: TestLab Predict
description: Predict CI results

inputs:
  predicted-tests-file:
    description: Path to the predicted tests file.
    default: /tmp/predicted-tests.json
    required: false
  repo-root:
    description: Root directory of the repository.
    required: false
  continue-on-error:
    description: Continue with CI workflow on error.
    type: boolean
    required: false
    default: true

runs:
  using: composite
  steps:
    - name: Predict CI results
      run: ${GITHUB_ACTION_PATH}/script.sh
      shell: bash
      continue-on-error: ${{ fromJSON(inputs.continue-on-error) }}
      env:
        PREDICTED_TESTS_FILE: ${{ inputs.predicted-tests-file }}
        REPO_ROOT: ${{ inputs.repo-root || github.workspace }}
