name: CI

on:
  pull_request:
  push:
    branches: [main]
    tags:
      - "*"

defaults:
  run:
    shell: bash

permissions:
  contents: write

jobs:
  ci:
    name: 'CI'
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Test action
        uses: ./
        with:
          continue-on-error: false
        env:
          TESTLAB_GROUP: unit
          TESTLAB_KEY: ${{ secrets.TESTLAB_KEY }}
